I vores første iteration af projektet var udgangspunktet use casen UC2 - 'Se ledige transportmidler for et bestemt tidspunkt'. For at kunne estimere implementeringen mere præcist, foldede vi den ud, så den blev flere mindre tasks. Vi oprettede domæneklasser for Car, Bike og Employee og dertilhørende json-filer. For at sikre en så fleksibel og vedligeholdelsesvenlig arkitektur som muligt, valgte vi at implementere et repository pattern. Formålet var at abstrahere dataadgangen, så applikationslaget ikke har direkte afhængighed til datakilden. Repositories kan virke overflødigt i vores indtil nu simple system, men gør det skalerbart til en fremtidig database som datakilde uden at skulle ændre logik i vores servicelag. Samtidig bidrager det til at holde vores domæneklasser rene og fri for datalagringslogik. Vi introducerede nu interfacet, IRepository T, fordi vi havde flere repositories med ens funktionalitet - de læser json-filerne og deserialiserer dem til objekter. For at undgå gentagelse oprettede vi den abstrakte FileHandler-klasse, som de tre konkrete repositories nedarver fra. Til at starte med implementerede vi en superklasse, BaseVehicleRepository, som CarRepository og BikeRepository nedarvede fra. Den blev introduceret for at kunne behandle forskellige transportmidler ens, da et Irepository Car ikke kunne anvendes som Irepository IVehicle. Med introduktionen af interfacet, IvehicleProvider, blev ansvaret flyttet væk fra superklassen, da det var interfacet, som VehicleService afhang af. Vores base-klasse gjorde det dog stadig muligt at genbruge logik mellem repositories.

Da vi senere indførte kovarians i `IRepository<T>`  ved at bruge (out T) og ændre returtypen til  `IEnumerable<T>` endte det med at skabe samme ønskede fleksibilitet, hvilket gjorde både IVehicleProvider og superklassen overflødige og muliggjorde, at de senere kunne fjernes.

Under implementeringen blev vi nemlig, med hjælp fra et genereret klassediagram, opmærksomme på den unødvendige kompleksitet i vores design, der gjorde ovennævnte klasse og interface overflødige. På dette tidspunkt bestod vores arkitektur stadig af to abstraktioner - IRepository T og IVehicleProvider, som servicelaget var afhængig af for at kunne håndtere forskellige transportmidler, da IRepository Car og IRepository Bike ikke kunne behandles som IRepository IVehicle. Klassediagrammet gjorde det tydeligt, at superklassen og IVehicleProvider kun eksisterede i systemet for at løse det problem. I et forsøg på at samle flere forskellige transportmidler under en struktur, implementerede vi klassen CompositeVehicleProvider, der samlede flere IVehicleProvider-instanser og fungerede som et composite pattern. Efter indplementeringen af kovarians blev det muligt at generalisere vores composite pattern og skabe `CompositeRepository<T>` som en generisk løsning. Med denne vigtige ændring blev designet åbent for nye samlinger af repositories i senere iterationer. Det betyder, at compileren nu tillader, at Car og Bike, samt alle fremtidige transportmidler, der implementerer IVehicle, kan behandles som IVehicle, og samtidig risikerer vi ikke, at vores employees bliver behandlet som transportmidler, fordi de ikke er en del af samme typehieraki.

Med indførelsen af kovarians kunne vi fjerne IVehicleProvider og BaseVehicleRepository og erstatte dem med en generisk `CompositeRepository<T>`. Det ender med at give os et generisk Composite Pattern, hvor servicelaget kan hente alle objekter af en type uden af kende til konkrete repositories.






